FROM ubuntu:19.10

RUN apt-get update
RUN apt-get install -y openjdk-13-jre 

RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* 


---
FROM ubuntu:19.10

RUN apt-get update \
    && apt-get install -y openjdk-13-jre \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
